<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE eagle SYSTEM "eagle.dtd">
<eagle version="9.6.2">
<drawing>
<settings>
<setting alwaysvectorfont="no"/>
<setting verticaltext="up"/>
</settings>
<grid distance="0.1" unitdist="inch" unit="inch" style="lines" multiple="1" display="no" altdistance="0.01" altunitdist="inch" altunit="inch"/>
<layers>
<layer number="1" name="Top" color="4" fill="1" visible="no" active="no"/>
<layer number="16" name="Bottom" color="1" fill="1" visible="no" active="no"/>
<layer number="17" name="Pads" color="2" fill="1" visible="no" active="no"/>
<layer number="18" name="Vias" color="2" fill="1" visible="no" active="no"/>
<layer number="19" name="Unrouted" color="6" fill="1" visible="no" active="no"/>
<layer number="20" name="Dimension" color="15" fill="1" visible="no" active="no"/>
<layer number="21" name="tPlace" color="7" fill="1" visible="no" active="no"/>
<layer number="22" name="bPlace" color="7" fill="1" visible="no" active="no"/>
<layer number="23" name="tOrigins" color="15" fill="1" visible="no" active="no"/>
<layer number="24" name="bOrigins" color="15" fill="1" visible="no" active="no"/>
<layer number="25" name="tNames" color="7" fill="1" visible="no" active="no"/>
<layer number="26" name="bNames" color="7" fill="1" visible="no" active="no"/>
<layer number="27" name="tValues" color="7" fill="1" visible="no" active="no"/>
<layer number="28" name="bValues" color="7" fill="1" visible="no" active="no"/>
<layer number="29" name="tStop" color="7" fill="3" visible="no" active="no"/>
<layer number="30" name="bStop" color="7" fill="6" visible="no" active="no"/>
<layer number="31" name="tCream" color="7" fill="4" visible="no" active="no"/>
<layer number="32" name="bCream" color="7" fill="5" visible="no" active="no"/>
<layer number="33" name="tFinish" color="6" fill="3" visible="no" active="no"/>
<layer number="34" name="bFinish" color="6" fill="6" visible="no" active="no"/>
<layer number="35" name="tGlue" color="7" fill="4" visible="no" active="no"/>
<layer number="36" name="bGlue" color="7" fill="5" visible="no" active="no"/>
<layer number="37" name="tTest" color="7" fill="1" visible="no" active="no"/>
<layer number="38" name="bTest" color="7" fill="1" visible="no" active="no"/>
<layer number="39" name="tKeepout" color="4" fill="11" visible="no" active="no"/>
<layer number="40" name="bKeepout" color="1" fill="11" visible="no" active="no"/>
<layer number="41" name="tRestrict" color="4" fill="10" visible="no" active="no"/>
<layer number="42" name="bRestrict" color="1" fill="10" visible="no" active="no"/>
<layer number="43" name="vRestrict" color="2" fill="10" visible="no" active="no"/>
<layer number="44" name="Drills" color="7" fill="1" visible="no" active="no"/>
<layer number="45" name="Holes" color="7" fill="1" visible="no" active="no"/>
<layer number="46" name="Milling" color="3" fill="1" visible="no" active="no"/>
<layer number="47" name="Measures" color="7" fill="1" visible="no" active="no"/>
<layer number="48" name="Document" color="7" fill="1" visible="no" active="no"/>
<layer number="49" name="Reference" color="7" fill="1" visible="no" active="no"/>
<layer number="51" name="tDocu" color="7" fill="1" visible="no" active="no"/>
<layer number="52" name="bDocu" color="7" fill="1" visible="no" active="no"/>
<layer number="88" name="SimResults" color="9" fill="1" visible="yes" active="yes"/>
<layer number="89" name="SimProbes" color="9" fill="1" visible="yes" active="yes"/>
<layer number="90" name="Modules" color="5" fill="1" visible="yes" active="yes"/>
<layer number="91" name="Nets" color="2" fill="1" visible="yes" active="yes"/>
<layer number="92" name="Busses" color="1" fill="1" visible="yes" active="yes"/>
<layer number="93" name="Pins" color="2" fill="1" visible="no" active="yes"/>
<layer number="94" name="Symbols" color="4" fill="1" visible="yes" active="yes"/>
<layer number="95" name="Names" color="7" fill="1" visible="yes" active="yes"/>
<layer number="96" name="Values" color="7" fill="1" visible="yes" active="yes"/>
<layer number="97" name="Info" color="7" fill="1" visible="yes" active="yes"/>
<layer number="98" name="Guide" color="6" fill="1" visible="yes" active="yes"/>
</layers>
<schematic xreflabel="%F%N/%S.%C%R" xrefpart="/%S.%C%R">
<libraries>
<library name="arduino">
<packages>
<package name="ARDUINO_NANO2">
<description>&lt;b&gt;Arduino Nano2&lt;/b&gt;&lt;p&gt;
Auto generated by &lt;i&gt;modulcreator.ulp&lt;/i&gt;&lt;br&gt;
\;</description>
<wire x1="-8.89" y1="-21.59" x2="8.89" y2="-21.59" width="0" layer="21"/>
<wire x1="8.89" y1="-21.59" x2="8.89" y2="21.59" width="0" layer="21"/>
<wire x1="8.89" y1="21.59" x2="-8.89" y2="21.59" width="0" layer="21"/>
<wire x1="-8.89" y1="21.59" x2="-8.89" y2="-21.59" width="0" layer="21"/>
<pad name="J1.1" x="-7.62" y="17.78" drill="0.9144" diameter="1.778" shape="square" rot="R270"/>
<pad name="J1.2" x="-7.62" y="15.24" drill="0.9144" diameter="1.778" rot="R270"/>
<pad name="J1.3" x="-7.62" y="12.7" drill="0.9144" diameter="1.778" rot="R270"/>
<pad name="J1.4" x="-7.62" y="10.16" drill="0.9144" diameter="1.778" rot="R270"/>
<pad name="J1.5" x="-7.62" y="7.62" drill="0.9144" diameter="1.778" rot="R270"/>
<pad name="J1.6" x="-7.62" y="5.08" drill="0.9144" diameter="1.778" rot="R270"/>
<pad name="J1.7" x="-7.62" y="2.54" drill="0.9144" diameter="1.778" rot="R270"/>
<pad name="J1.8" x="-7.62" y="0" drill="0.9144" diameter="1.778" rot="R270"/>
<pad name="J1.9" x="-7.62" y="-2.54" drill="0.9144" diameter="1.778" rot="R270"/>
<pad name="J1.10" x="-7.62" y="-5.08" drill="0.9144" diameter="1.778" rot="R270"/>
<pad name="J1.11" x="-7.62" y="-7.62" drill="0.9144" diameter="1.778" rot="R270"/>
<pad name="J1.12" x="-7.62" y="-10.16" drill="0.9144" diameter="1.778" rot="R270"/>
<pad name="J1.13" x="-7.62" y="-12.7" drill="0.9144" diameter="1.778" rot="R270"/>
<pad name="J1.14" x="-7.62" y="-15.24" drill="0.9144" diameter="1.778" rot="R270"/>
<pad name="J1.15" x="-7.62" y="-17.78" drill="0.9144" diameter="1.778" rot="R270"/>
<pad name="J2.1" x="7.62" y="17.78" drill="0.9144" diameter="1.778" rot="R270"/>
<pad name="J2.2" x="7.62" y="15.24" drill="0.9144" diameter="1.778" rot="R270"/>
<pad name="J2.3" x="7.62" y="12.7" drill="0.9144" diameter="1.778" rot="R270"/>
<pad name="J2.4" x="7.62" y="10.16" drill="0.9144" diameter="1.778" rot="R270"/>
<pad name="J2.5" x="7.62" y="7.62" drill="0.9144" diameter="1.778" rot="R270"/>
<pad name="J2.6" x="7.62" y="5.08" drill="0.9144" diameter="1.778" rot="R270"/>
<pad name="J2.7" x="7.62" y="2.54" drill="0.9144" diameter="1.778" rot="R270"/>
<pad name="J2.8" x="7.62" y="0" drill="0.9144" diameter="1.778" rot="R270"/>
<pad name="J2.9" x="7.62" y="-2.54" drill="0.9144" diameter="1.778" rot="R270"/>
<pad name="J2.10" x="7.62" y="-5.08" drill="0.9144" diameter="1.778" rot="R270"/>
<pad name="J2.11" x="7.62" y="-7.62" drill="0.9144" diameter="1.778" rot="R270"/>
<pad name="J2.12" x="7.62" y="-10.16" drill="0.9144" diameter="1.778" rot="R270"/>
<pad name="J2.13" x="7.62" y="-12.7" drill="0.9144" diameter="1.778" rot="R270"/>
<pad name="J2.14" x="7.62" y="-15.24" drill="0.9144" diameter="1.778" rot="R270"/>
<pad name="J2.15" x="7.62" y="-17.78" drill="0.9144" diameter="1.778" rot="R270"/>
<text x="0" y="19.6" size="1" layer="25" font="vector">&gt;NAME</text>
<text x="0" y="-19.6" size="1" layer="27" font="vector">&gt;VALUE</text>
<hole x="-7.62" y="-20.32" drill="1.651"/>
<hole x="7.62" y="-20.32" drill="1.651"/>
<hole x="7.62" y="20.32" drill="1.651"/>
<hole x="-7.62" y="20.32" drill="1.651"/>
</package>
</packages>
<symbols>
<symbol name="ARDUINO_NANO2">
<wire x1="-20.32" y1="30.48" x2="20.32" y2="30.48" width="0.254" layer="94"/>
<wire x1="20.32" y1="30.48" x2="20.32" y2="-30.48" width="0.254" layer="94"/>
<wire x1="20.32" y1="-30.48" x2="-20.32" y2="-30.48" width="0.254" layer="94"/>
<wire x1="-20.32" y1="-30.48" x2="-20.32" y2="30.48" width="0.254" layer="94"/>
<text x="-17.78" y="-25.4" size="1.778" layer="95">&gt;NAME</text>
<text x="-17.78" y="-27.94" size="1.778" layer="96">&gt;VALUE</text>
<pin name="D1/TX" x="25.4" y="27.94" length="middle" rot="R180"/>
<pin name="D0/RX" x="25.4" y="25.4" length="middle" rot="R180"/>
<pin name="RESET" x="-25.4" y="20.32" length="middle"/>
<pin name="COM" x="-2.54" y="-35.56" length="middle" direction="pwr" rot="R90"/>
<pin name="D2" x="25.4" y="22.86" length="middle" rot="R180"/>
<pin name="D3" x="25.4" y="20.32" length="middle" rot="R180"/>
<pin name="D4" x="25.4" y="17.78" length="middle" rot="R180"/>
<pin name="D5" x="25.4" y="15.24" length="middle" rot="R180"/>
<pin name="D6" x="25.4" y="12.7" length="middle" rot="R180"/>
<pin name="D7" x="25.4" y="10.16" length="middle" rot="R180"/>
<pin name="D8" x="25.4" y="7.62" length="middle" rot="R180"/>
<pin name="D9" x="25.4" y="5.08" length="middle" rot="R180"/>
<pin name="D10" x="25.4" y="2.54" length="middle" rot="R180"/>
<pin name="D11/MOSI" x="25.4" y="0" length="middle" rot="R180"/>
<pin name="D12/MISO" x="25.4" y="-2.54" length="middle" rot="R180"/>
<pin name="VIN" x="-10.16" y="35.56" length="middle" direction="pwr" rot="R270"/>
<pin name="COM@1" x="5.08" y="-35.56" length="middle" direction="pwr" rot="R90"/>
<pin name="RESET@2" x="-25.4" y="17.78" length="middle"/>
<pin name="+5V" x="-5.08" y="35.56" length="middle" direction="pwr" rot="R270"/>
<pin name="A7" x="25.4" y="-10.16" length="middle" rot="R180"/>
<pin name="A6" x="25.4" y="-12.7" length="middle" rot="R180"/>
<pin name="A5" x="25.4" y="-15.24" length="middle" rot="R180"/>
<pin name="A4" x="25.4" y="-17.78" length="middle" rot="R180"/>
<pin name="A3" x="25.4" y="-20.32" length="middle" rot="R180"/>
<pin name="A2" x="25.4" y="-22.86" length="middle" rot="R180"/>
<pin name="A1" x="25.4" y="-25.4" length="middle" rot="R180"/>
<pin name="A0" x="25.4" y="-27.94" length="middle" rot="R180"/>
<pin name="AREF" x="7.62" y="35.56" length="middle" direction="pwr" rot="R270"/>
<pin name="3V3" x="2.54" y="35.56" length="middle" direction="pwr" rot="R270"/>
<pin name="D13/SCK" x="25.4" y="-5.08" length="middle" rot="R180"/>
</symbol>
</symbols>
<devicesets>
<deviceset name="ARDUINO_NANO2" prefix="MODUL">
<description>&lt;b&gt;Arduino Nano2&lt;/b&gt;&lt;p&gt;
Auto generated by &lt;i&gt;modulcreator.ulp&lt;/i&gt;&lt;br&gt;
\;</description>
<gates>
<gate name="MODUL" symbol="ARDUINO_NANO2" x="0" y="0"/>
</gates>
<devices>
<device name="" package="ARDUINO_NANO2">
<connects>
<connect gate="MODUL" pin="+5V" pad="J2.4"/>
<connect gate="MODUL" pin="3V3" pad="J2.14"/>
<connect gate="MODUL" pin="A0" pad="J2.12"/>
<connect gate="MODUL" pin="A1" pad="J2.11"/>
<connect gate="MODUL" pin="A2" pad="J2.10"/>
<connect gate="MODUL" pin="A3" pad="J2.9"/>
<connect gate="MODUL" pin="A4" pad="J2.8"/>
<connect gate="MODUL" pin="A5" pad="J2.7"/>
<connect gate="MODUL" pin="A6" pad="J2.6"/>
<connect gate="MODUL" pin="A7" pad="J2.5"/>
<connect gate="MODUL" pin="AREF" pad="J2.13"/>
<connect gate="MODUL" pin="COM" pad="J1.4"/>
<connect gate="MODUL" pin="COM@1" pad="J2.2"/>
<connect gate="MODUL" pin="D0/RX" pad="J1.2"/>
<connect gate="MODUL" pin="D1/TX" pad="J1.1"/>
<connect gate="MODUL" pin="D10" pad="J1.13"/>
<connect gate="MODUL" pin="D11/MOSI" pad="J1.14"/>
<connect gate="MODUL" pin="D12/MISO" pad="J1.15"/>
<connect gate="MODUL" pin="D13/SCK" pad="J2.15"/>
<connect gate="MODUL" pin="D2" pad="J1.5"/>
<connect gate="MODUL" pin="D3" pad="J1.6"/>
<connect gate="MODUL" pin="D4" pad="J1.7"/>
<connect gate="MODUL" pin="D5" pad="J1.8"/>
<connect gate="MODUL" pin="D6" pad="J1.9"/>
<connect gate="MODUL" pin="D7" pad="J1.10"/>
<connect gate="MODUL" pin="D8" pad="J1.11"/>
<connect gate="MODUL" pin="D9" pad="J1.12"/>
<connect gate="MODUL" pin="RESET" pad="J1.3"/>
<connect gate="MODUL" pin="RESET@2" pad="J2.3"/>
<connect gate="MODUL" pin="VIN" pad="J2.1"/>
</connects>
<technologies>
<technology name="">
<attribute name="ANZAHL" value="2"/>
<attribute name="MODUL" value="TRUE"/>
<attribute name="STECKPSI0" value=""/>
<attribute name="STECKPSI1" value=""/>
<attribute name="STECKX0" value="-76200"/>
<attribute name="STECKX1" value="76200"/>
<attribute name="STECKY0" value="177800"/>
<attribute name="STECKY1" value="177800"/>
</technology>
</technologies>
</device>
</devices>
</deviceset>
</devicesets>
</library>
<library name="supply2" urn="urn:adsk.eagle:library:372">
<description>&lt;b&gt;Supply Symbols&lt;/b&gt;&lt;p&gt;
GND, VCC, 0V, +5V, -5V, etc.&lt;p&gt;
Please keep in mind, that these devices are necessary for the
automatic wiring of the supply signals.&lt;p&gt;
The pin name defined in the symbol is identical to the net which is to be wired automatically.&lt;p&gt;
In this library the device names are the same as the pin names of the symbols, therefore the correct signal names appear next to the supply symbols in the schematic.&lt;p&gt;
&lt;author&gt;Created by librarian@cadsoft.de&lt;/author&gt;</description>
<packages>
</packages>
<symbols>
<symbol name="GND" urn="urn:adsk.eagle:symbol:26990/1" library_version="2">
<wire x1="-1.27" y1="0" x2="1.27" y2="0" width="0.254" layer="94"/>
<wire x1="1.27" y1="0" x2="0" y2="-1.27" width="0.254" layer="94"/>
<wire x1="0" y1="-1.27" x2="-1.27" y2="0" width="0.254" layer="94"/>
<text x="-1.905" y="-3.175" size="1.778" layer="96">&gt;VALUE</text>
<pin name="GND" x="0" y="2.54" visible="off" length="short" direction="sup" rot="R270"/>
</symbol>
</symbols>
<devicesets>
<deviceset name="GND" urn="urn:adsk.eagle:component:27037/1" prefix="SUPPLY" library_version="2">
<description>&lt;b&gt;SUPPLY SYMBOL&lt;/b&gt;</description>
<gates>
<gate name="GND" symbol="GND" x="0" y="0"/>
</gates>
<devices>
<device name="">
<technologies>
<technology name=""/>
</technologies>
</device>
</devices>
</deviceset>
</devicesets>
</library>
<library name="supply1" urn="urn:adsk.eagle:library:371">
<description>&lt;b&gt;Supply Symbols&lt;/b&gt;&lt;p&gt;
 GND, VCC, 0V, +5V, -5V, etc.&lt;p&gt;
 Please keep in mind, that these devices are necessary for the
 automatic wiring of the supply signals.&lt;p&gt;
 The pin name defined in the symbol is identical to the net which is to be wired automatically.&lt;p&gt;
 In this library the device names are the same as the pin names of the symbols, therefore the correct signal names appear next to the supply symbols in the schematic.&lt;p&gt;
 &lt;author&gt;Created by librarian@cadsoft.de&lt;/author&gt;</description>
<packages>
</packages>
<symbols>
<symbol name="VCC" urn="urn:adsk.eagle:symbol:26928/1" library_version="1">
<wire x1="1.27" y1="-1.905" x2="0" y2="0" width="0.254" layer="94"/>
<wire x1="0" y1="0" x2="-1.27" y2="-1.905" width="0.254" layer="94"/>
<text x="-2.54" y="-2.54" size="1.778" layer="96" rot="R90">&gt;VALUE</text>
<pin name="VCC" x="0" y="-2.54" visible="off" length="short" direction="sup" rot="R90"/>
</symbol>
</symbols>
<devicesets>
<deviceset name="VCC" urn="urn:adsk.eagle:component:26957/1" prefix="P+" library_version="1">
<description>&lt;b&gt;SUPPLY SYMBOL&lt;/b&gt;</description>
<gates>
<gate name="VCC" symbol="VCC" x="0" y="0"/>
</gates>
<devices>
<device name="">
<technologies>
<technology name=""/>
</technologies>
</device>
</devices>
</deviceset>
</devicesets>
</library>
<library name="con-amp" urn="urn:adsk.eagle:library:127">
<description>&lt;b&gt;AMP Connectors&lt;/b&gt;&lt;p&gt;
RJ45 Jack connectors&lt;br&gt;
 Based on the previous libraris:
 &lt;ul&gt;
 &lt;li&gt;amp.lbr
 &lt;li&gt;amp-j.lbr
 &lt;li&gt;amp-mta.lbr
 &lt;li&gt;amp-nlok.lbr
 &lt;li&gt;amp-sim.lbr
 &lt;li&gt;amp-micro-match.lbr
 &lt;/ul&gt;
 Sources :
 &lt;ul&gt;
 &lt;li&gt;Catalog 82066 Revised 11-95 
 &lt;li&gt;Product Guide 296785 Rev. 8-99
 &lt;li&gt;Product Guide CD-ROM 1999
 &lt;li&gt;www.amp.com
 &lt;/ul&gt;
 &lt;author&gt;Created by librarian@cadsoft.de&lt;/author&gt;</description>
<packages>
<package name="10X05MTA" urn="urn:adsk.eagle:footprint:8080326/1" library_version="4">
<description>&lt;b&gt;AMP MTA connector&lt;/b&gt;&lt;p&gt;
Source: http://ecommas.tycoelectronics.com .. ENG_CD_640456_W.pdf</description>
<wire x1="-6.35" y1="-1.27" x2="-6.35" y2="1.27" width="0.1524" layer="21"/>
<wire x1="6.35" y1="1.27" x2="-6.35" y2="1.27" width="0.1524" layer="21"/>
<wire x1="6.35" y1="1.27" x2="6.35" y2="-1.27" width="0.1524" layer="21"/>
<wire x1="-6.35" y1="-1.27" x2="6.35" y2="-1.27" width="0.1524" layer="21"/>
<wire x1="-6.35" y1="1.27" x2="-6.35" y2="1.905" width="0.1524" layer="21"/>
<wire x1="6.35" y1="1.905" x2="-6.35" y2="1.905" width="0.1524" layer="21"/>
<wire x1="6.35" y1="1.905" x2="6.35" y2="1.27" width="0.1524" layer="21"/>
<pad name="5" x="-5.08" y="0" drill="1.016" shape="long" rot="R90"/>
<pad name="4" x="-2.54" y="0" drill="1.016" shape="long" rot="R90"/>
<pad name="3" x="0" y="0" drill="1.016" shape="long" rot="R90"/>
<pad name="2" x="2.54" y="0" drill="1.016" shape="long" rot="R90"/>
<pad name="1" x="5.08" y="0" drill="1.016" shape="long" rot="R90"/>
<text x="-2.6162" y="-3.2512" size="1.27" layer="25">&gt;NAME</text>
<text x="-6.1763" y="2.1509" size="1.27" layer="27">&gt;VALUE</text>
<rectangle x1="-0.254" y1="-0.254" x2="0.254" y2="0.254" layer="21"/>
<rectangle x1="-2.794" y1="-0.254" x2="-2.286" y2="0.254" layer="21"/>
<rectangle x1="-5.334" y1="-0.254" x2="-4.826" y2="0.254" layer="21"/>
<rectangle x1="2.286" y1="-0.254" x2="2.794" y2="0.254" layer="21"/>
<rectangle x1="4.826" y1="-0.254" x2="5.334" y2="0.254" layer="21"/>
</package>
<package name="10X06MTA" urn="urn:adsk.eagle:footprint:8080327/1" library_version="4">
<description>&lt;b&gt;AMP MTA connector&lt;/b&gt;&lt;p&gt;
Source: http://ecommas.tycoelectronics.com .. ENG_CD_640456_W.pdf</description>
<wire x1="-7.62" y1="-1.27" x2="-7.62" y2="1.27" width="0.1524" layer="21"/>
<wire x1="7.62" y1="1.27" x2="-7.62" y2="1.27" width="0.1524" layer="21"/>
<wire x1="7.62" y1="1.27" x2="7.62" y2="-1.27" width="0.1524" layer="21"/>
<wire x1="-7.62" y1="-1.27" x2="7.62" y2="-1.27" width="0.1524" layer="21"/>
<wire x1="-7.62" y1="1.27" x2="-7.62" y2="1.905" width="0.1524" layer="21"/>
<wire x1="7.62" y1="1.905" x2="-7.62" y2="1.905" width="0.1524" layer="21"/>
<wire x1="7.62" y1="1.905" x2="7.62" y2="1.27" width="0.1524" layer="21"/>
<pad name="6" x="-6.35" y="0" drill="1.016" shape="long" rot="R90"/>
<pad name="5" x="-3.81" y="0" drill="1.016" shape="long" rot="R90"/>
<pad name="4" x="-1.27" y="0" drill="1.016" shape="long" rot="R90"/>
<pad name="3" x="1.27" y="0" drill="1.016" shape="long" rot="R90"/>
<pad name="2" x="3.81" y="0" drill="1.016" shape="long" rot="R90"/>
<pad name="1" x="6.35" y="0" drill="1.016" shape="long" rot="R90"/>
<text x="-2.6162" y="-3.2512" size="1.27" layer="25">&gt;NAME</text>
<text x="-7.4762" y="2.2507" size="1.27" layer="27">&gt;VALUE</text>
<rectangle x1="-1.524" y1="-0.254" x2="-1.016" y2="0.254" layer="21"/>
<rectangle x1="-4.064" y1="-0.254" x2="-3.556" y2="0.254" layer="21"/>
<rectangle x1="-6.604" y1="-0.254" x2="-6.096" y2="0.254" layer="21"/>
<rectangle x1="1.016" y1="-0.254" x2="1.524" y2="0.254" layer="21"/>
<rectangle x1="3.556" y1="-0.254" x2="4.064" y2="0.254" layer="21"/>
<rectangle x1="6.096" y1="-0.254" x2="6.604" y2="0.254" layer="21"/>
</package>
<package name="10X08MTA" urn="urn:adsk.eagle:footprint:8080335/1" library_version="4">
<description>&lt;b&gt;AMP MTA connector&lt;/b&gt;&lt;p&gt;
Source: http://ecommas.tycoelectronics.com .. ENG_CD_640456_W.pdf</description>
<wire x1="-10.16" y1="-1.27" x2="-10.16" y2="1.27" width="0.1524" layer="21"/>
<wire x1="10.16" y1="1.27" x2="-10.16" y2="1.27" width="0.1524" layer="21"/>
<wire x1="10.16" y1="1.27" x2="10.16" y2="-1.27" width="0.1524" layer="21"/>
<wire x1="-10.16" y1="-1.27" x2="10.16" y2="-1.27" width="0.1524" layer="21"/>
<wire x1="-10.16" y1="1.27" x2="-10.16" y2="1.905" width="0.1524" layer="21"/>
<wire x1="10.16" y1="1.905" x2="-10.16" y2="1.905" width="0.1524" layer="21"/>
<wire x1="10.16" y1="1.905" x2="10.16" y2="1.27" width="0.1524" layer="21"/>
<pad name="7" x="-6.35" y="0" drill="1.016" shape="long" rot="R90"/>
<pad name="6" x="-3.81" y="0" drill="1.016" shape="long" rot="R90"/>
<pad name="5" x="-1.27" y="0" drill="1.016" shape="long" rot="R90"/>
<pad name="4" x="1.27" y="0" drill="1.016" shape="long" rot="R90"/>
<pad name="3" x="3.81" y="0" drill="1.016" shape="long" rot="R90"/>
<pad name="2" x="6.35" y="0" drill="1.016" shape="long" rot="R90"/>
<pad name="1" x="8.89" y="0" drill="1.016" shape="long" rot="R90"/>
<pad name="8" x="-8.89" y="0" drill="1.016" shape="long" rot="R90"/>
<text x="-1.9812" y="-3.2512" size="1.27" layer="25">&gt;NAME</text>
<text x="-10.0762" y="2.2507" size="1.27" layer="27">&gt;VALUE</text>
<rectangle x1="-1.524" y1="-0.254" x2="-1.016" y2="0.254" layer="21"/>
<rectangle x1="-4.064" y1="-0.254" x2="-3.556" y2="0.254" layer="21"/>
<rectangle x1="-6.604" y1="-0.254" x2="-6.096" y2="0.254" layer="21"/>
<rectangle x1="1.016" y1="-0.254" x2="1.524" y2="0.254" layer="21"/>
<rectangle x1="3.556" y1="-0.254" x2="4.064" y2="0.254" layer="21"/>
<rectangle x1="6.096" y1="-0.254" x2="6.604" y2="0.254" layer="21"/>
<rectangle x1="8.636" y1="-0.254" x2="9.144" y2="0.254" layer="21"/>
<rectangle x1="-9.144" y1="-0.254" x2="-8.636" y2="0.254" layer="21"/>
</package>
<package name="10X10MTA" urn="urn:adsk.eagle:footprint:8080359/1" library_version="4">
<description>&lt;b&gt;AMP MTA connector&lt;/b&gt;&lt;p&gt;
Source: http://ecommas.tycoelectronics.com .. ENG_CD_640456_W.pdf</description>
<wire x1="-12.7" y1="-1.27" x2="-12.7" y2="1.27" width="0.1524" layer="21"/>
<wire x1="12.7" y1="1.27" x2="-12.7" y2="1.27" width="0.1524" layer="21"/>
<wire x1="12.7" y1="1.27" x2="12.7" y2="-1.27" width="0.1524" layer="21"/>
<wire x1="-12.7" y1="-1.27" x2="12.7" y2="-1.27" width="0.1524" layer="21"/>
<wire x1="-12.7" y1="1.27" x2="-12.7" y2="1.905" width="0.1524" layer="21"/>
<wire x1="12.7" y1="1.905" x2="-12.7" y2="1.905" width="0.1524" layer="21"/>
<wire x1="12.7" y1="1.905" x2="12.7" y2="1.27" width="0.1524" layer="21"/>
<pad name="7" x="-3.81" y="0" drill="1.016" shape="long" rot="R90"/>
<pad name="6" x="-1.27" y="0" drill="1.016" shape="long" rot="R90"/>
<pad name="5" x="1.27" y="0" drill="1.016" shape="long" rot="R90"/>
<pad name="4" x="3.81" y="0" drill="1.016" shape="long" rot="R90"/>
<pad name="3" x="6.35" y="0" drill="1.016" shape="long" rot="R90"/>
<pad name="2" x="8.89" y="0" drill="1.016" shape="long" rot="R90"/>
<pad name="1" x="11.43" y="0" drill="1.016" shape="long" rot="R90"/>
<pad name="8" x="-6.35" y="0" drill="1.016" shape="long" rot="R90"/>
<pad name="9" x="-8.89" y="0" drill="1.016" shape="long" rot="R90"/>
<pad name="10" x="-11.43" y="0" drill="1.016" shape="long" rot="R90"/>
<text x="-2.6162" y="-3.2512" size="1.27" layer="25">&gt;NAME</text>
<text x="-12.4762" y="2.2507" size="1.27" layer="27">&gt;VALUE</text>
<rectangle x1="1.016" y1="-0.254" x2="1.524" y2="0.254" layer="21"/>
<rectangle x1="-1.524" y1="-0.254" x2="-1.016" y2="0.254" layer="21"/>
<rectangle x1="-4.064" y1="-0.254" x2="-3.556" y2="0.254" layer="21"/>
<rectangle x1="3.556" y1="-0.254" x2="4.064" y2="0.254" layer="21"/>
<rectangle x1="6.096" y1="-0.254" x2="6.604" y2="0.254" layer="21"/>
<rectangle x1="8.636" y1="-0.254" x2="9.144" y2="0.254" layer="21"/>
<rectangle x1="11.176" y1="-0.254" x2="11.684" y2="0.254" layer="21"/>
<rectangle x1="-6.604" y1="-0.254" x2="-6.096" y2="0.254" layer="21"/>
<rectangle x1="-9.144" y1="-0.254" x2="-8.636" y2="0.254" layer="21"/>
<rectangle x1="-11.684" y1="-0.254" x2="-11.176" y2="0.254" layer="21"/>
</package>
</packages>
<packages3d>
<package3d name="10X05MTA" urn="urn:adsk.eagle:package:8081622/1" type="box" library_version="4">
<description>&lt;b&gt;AMP MTA connector&lt;/b&gt;&lt;p&gt;
Source: http://ecommas.tycoelectronics.com .. ENG_CD_640456_W.pdf</description>
<packageinstances>
<packageinstance name="10X05MTA"/>
</packageinstances>
</package3d>
<package3d name="10X06MTA" urn="urn:adsk.eagle:package:8081635/1" type="box" library_version="4">
<description>&lt;b&gt;AMP MTA connector&lt;/b&gt;&lt;p&gt;
Source: http://ecommas.tycoelectronics.com .. ENG_CD_640456_W.pdf</description>
<packageinstances>
<packageinstance name="10X06MTA"/>
</packageinstances>
</package3d>
<package3d name="10X08MTA" urn="urn:adsk.eagle:package:8081637/1" type="box" library_version="4">
<description>&lt;b&gt;AMP MTA connector&lt;/b&gt;&lt;p&gt;
Source: http://ecommas.tycoelectronics.com .. ENG_CD_640456_W.pdf</description>
<packageinstances>
<packageinstance name="10X08MTA"/>
</packageinstances>
</package3d>
<package3d name="10X10MTA" urn="urn:adsk.eagle:package:8081639/1" type="box" library_version="4">
<description>&lt;b&gt;AMP MTA connector&lt;/b&gt;&lt;p&gt;
Source: http://ecommas.tycoelectronics.com .. ENG_CD_640456_W.pdf</description>
<packageinstances>
<packageinstance name="10X10MTA"/>
</packageinstances>
</package3d>
</packages3d>
<symbols>
<symbol name="MTA-1_5" urn="urn:adsk.eagle:symbol:8079834/1" library_version="4">
<wire x1="-6.35" y1="1.27" x2="-6.35" y2="-1.905" width="0.254" layer="94"/>
<wire x1="6.35" y1="-1.905" x2="-6.35" y2="-1.905" width="0.254" layer="94"/>
<wire x1="6.35" y1="-1.905" x2="6.35" y2="1.27" width="0.254" layer="94"/>
<wire x1="-6.35" y1="1.27" x2="6.35" y2="1.27" width="0.254" layer="94"/>
<circle x="-5.08" y="0" radius="0.635" width="0.254" layer="94"/>
<circle x="-2.54" y="0" radius="0.635" width="0.254" layer="94"/>
<circle x="0" y="0" radius="0.635" width="0.254" layer="94"/>
<circle x="2.54" y="0" radius="0.635" width="0.254" layer="94"/>
<circle x="5.08" y="0" radius="0.635" width="0.254" layer="94"/>
<text x="7.62" y="0" size="1.778" layer="95">&gt;NAME</text>
<text x="7.62" y="-3.81" size="1.778" layer="96">&gt;VALUE</text>
<text x="-7.62" y="-1.27" size="1.27" layer="95">1</text>
<pin name="1" x="-5.08" y="-2.54" visible="off" length="short" direction="pas" rot="R90"/>
<pin name="2" x="-2.54" y="-2.54" visible="off" length="short" direction="pas" rot="R90"/>
<pin name="3" x="0" y="-2.54" visible="off" length="short" direction="pas" rot="R90"/>
<pin name="4" x="2.54" y="-2.54" visible="off" length="short" direction="pas" rot="R90"/>
<pin name="5" x="5.08" y="-2.54" visible="off" length="short" direction="pas" rot="R90"/>
</symbol>
<symbol name="MTA-1_6" urn="urn:adsk.eagle:symbol:8079835/1" library_version="4">
<wire x1="-6.35" y1="1.27" x2="-6.35" y2="-1.905" width="0.254" layer="94"/>
<wire x1="8.89" y1="-1.905" x2="-6.35" y2="-1.905" width="0.254" layer="94"/>
<wire x1="8.89" y1="-1.905" x2="8.89" y2="1.27" width="0.254" layer="94"/>
<wire x1="-6.35" y1="1.27" x2="8.89" y2="1.27" width="0.254" layer="94"/>
<circle x="-5.08" y="0" radius="0.635" width="0.254" layer="94"/>
<circle x="-2.54" y="0" radius="0.635" width="0.254" layer="94"/>
<circle x="0" y="0" radius="0.635" width="0.254" layer="94"/>
<circle x="2.54" y="0" radius="0.635" width="0.254" layer="94"/>
<circle x="5.08" y="0" radius="0.635" width="0.254" layer="94"/>
<circle x="7.62" y="0" radius="0.635" width="0.254" layer="94"/>
<text x="10.16" y="0" size="1.778" layer="95">&gt;NAME</text>
<text x="10.16" y="-3.81" size="1.778" layer="96">&gt;VALUE</text>
<text x="-7.62" y="-1.27" size="1.27" layer="95">1</text>
<pin name="1" x="-5.08" y="-2.54" visible="off" length="short" direction="pas" rot="R90"/>
<pin name="2" x="-2.54" y="-2.54" visible="off" length="short" direction="pas" rot="R90"/>
<pin name="3" x="0" y="-2.54" visible="off" length="short" direction="pas" rot="R90"/>
<pin name="4" x="2.54" y="-2.54" visible="off" length="short" direction="pas" rot="R90"/>
<pin name="5" x="5.08" y="-2.54" visible="off" length="short" direction="pas" rot="R90"/>
<pin name="6" x="7.62" y="-2.54" visible="off" length="short" direction="pas" rot="R90"/>
</symbol>
<symbol name="MTA-1_8" urn="urn:adsk.eagle:symbol:8079837/1" library_version="4">
<wire x1="-8.89" y1="1.27" x2="-8.89" y2="-1.905" width="0.254" layer="94"/>
<wire x1="11.43" y1="-1.905" x2="-8.89" y2="-1.905" width="0.254" layer="94"/>
<wire x1="11.43" y1="-1.905" x2="11.43" y2="1.27" width="0.254" layer="94"/>
<wire x1="-8.89" y1="1.27" x2="11.43" y2="1.27" width="0.254" layer="94"/>
<circle x="-7.62" y="0" radius="0.635" width="0.254" layer="94"/>
<circle x="-5.08" y="0" radius="0.635" width="0.254" layer="94"/>
<circle x="-2.54" y="0" radius="0.635" width="0.254" layer="94"/>
<circle x="0" y="0" radius="0.635" width="0.254" layer="94"/>
<circle x="2.54" y="0" radius="0.635" width="0.254" layer="94"/>
<circle x="5.08" y="0" radius="0.635" width="0.254" layer="94"/>
<circle x="7.62" y="0" radius="0.635" width="0.254" layer="94"/>
<circle x="10.16" y="0" radius="0.635" width="0.254" layer="94"/>
<text x="12.7" y="0" size="1.778" layer="95">&gt;NAME</text>
<text x="12.7" y="-3.81" size="1.778" layer="96">&gt;VALUE</text>
<text x="-8.89" y="0" size="1.27" layer="95" rot="R180">1</text>
<pin name="1" x="-7.62" y="-2.54" visible="off" length="short" direction="pas" rot="R90"/>
<pin name="2" x="-5.08" y="-2.54" visible="off" length="short" direction="pas" rot="R90"/>
<pin name="3" x="-2.54" y="-2.54" visible="off" length="short" direction="pas" rot="R90"/>
<pin name="4" x="0" y="-2.54" visible="off" length="short" direction="pas" rot="R90"/>
<pin name="5" x="2.54" y="-2.54" visible="off" length="short" direction="pas" rot="R90"/>
<pin name="6" x="5.08" y="-2.54" visible="off" length="short" direction="pas" rot="R90"/>
<pin name="7" x="7.62" y="-2.54" visible="off" length="short" direction="pas" rot="R90"/>
<pin name="8" x="10.16" y="-2.54" visible="off" length="short" direction="pas" rot="R90"/>
</symbol>
<symbol name="MTA-1_10" urn="urn:adsk.eagle:symbol:8079839/1" library_version="4">
<wire x1="-11.43" y1="1.27" x2="-11.43" y2="-1.905" width="0.254" layer="94"/>
<wire x1="13.97" y1="-1.905" x2="-11.43" y2="-1.905" width="0.254" layer="94"/>
<wire x1="13.97" y1="-1.905" x2="13.97" y2="1.27" width="0.254" layer="94"/>
<wire x1="-11.43" y1="1.27" x2="13.97" y2="1.27" width="0.254" layer="94"/>
<circle x="-10.16" y="0" radius="0.635" width="0.254" layer="94"/>
<circle x="-7.62" y="0" radius="0.635" width="0.254" layer="94"/>
<circle x="-5.08" y="0" radius="0.635" width="0.254" layer="94"/>
<circle x="-2.54" y="0" radius="0.635" width="0.254" layer="94"/>
<circle x="0" y="0" radius="0.635" width="0.254" layer="94"/>
<circle x="2.54" y="0" radius="0.635" width="0.254" layer="94"/>
<circle x="5.08" y="0" radius="0.635" width="0.254" layer="94"/>
<circle x="7.62" y="0" radius="0.635" width="0.254" layer="94"/>
<circle x="10.16" y="0" radius="0.635" width="0.254" layer="94"/>
<circle x="12.7" y="0" radius="0.635" width="0.254" layer="94"/>
<text x="15.24" y="0" size="1.778" layer="95">&gt;NAME</text>
<text x="-11.43" y="0" size="1.27" layer="95" rot="R180">1</text>
<text x="15.24" y="-3.81" size="1.778" layer="96">&gt;VALUE</text>
<pin name="1" x="-10.16" y="-2.54" visible="off" length="short" direction="pas" rot="R90"/>
<pin name="2" x="-7.62" y="-2.54" visible="off" length="short" direction="pas" rot="R90"/>
<pin name="3" x="-5.08" y="-2.54" visible="off" length="short" direction="pas" rot="R90"/>
<pin name="4" x="-2.54" y="-2.54" visible="off" length="short" direction="pas" rot="R90"/>
<pin name="5" x="0" y="-2.54" visible="off" length="short" direction="pas" rot="R90"/>
<pin name="6" x="2.54" y="-2.54" visible="off" length="short" direction="pas" rot="R90"/>
<pin name="7" x="5.08" y="-2.54" visible="off" length="short" direction="pas" rot="R90"/>
<pin name="8" x="7.62" y="-2.54" visible="off" length="short" direction="pas" rot="R90"/>
<pin name="9" x="10.16" y="-2.54" visible="off" length="short" direction="pas" rot="R90"/>
<pin name="10" x="12.7" y="-2.54" visible="off" length="short" direction="pas" rot="R90"/>
</symbol>
</symbols>
<devicesets>
<deviceset name="MTA05-100" urn="urn:adsk.eagle:component:8082802/2" prefix="J" uservalue="yes" library_version="4">
<description>&lt;b&gt;AMP connector&lt;/b&gt;</description>
<gates>
<gate name="G$1" symbol="MTA-1_5" x="-2.54" y="0"/>
</gates>
<devices>
<device name="" package="10X05MTA">
<connects>
<connect gate="G$1" pin="1" pad="1"/>
<connect gate="G$1" pin="2" pad="2"/>
<connect gate="G$1" pin="3" pad="3"/>
<connect gate="G$1" pin="4" pad="4"/>
<connect gate="G$1" pin="5" pad="5"/>
</connects>
<package3dinstances>
<package3dinstance package3d_urn="urn:adsk.eagle:package:8081622/1"/>
</package3dinstances>
<technologies>
<technology name="">
<attribute name="POPULARITY" value="0" constant="no"/>
</technology>
</technologies>
</device>
</devices>
</deviceset>
<deviceset name="MTA06-100" urn="urn:adsk.eagle:component:8082803/2" prefix="J" uservalue="yes" library_version="4">
<description>&lt;b&gt;AMP connector&lt;/b&gt;&lt;p&gt;
Connection corrected 2014-09-19</description>
<gates>
<gate name="G$1" symbol="MTA-1_6" x="0" y="0"/>
</gates>
<devices>
<device name="" package="10X06MTA">
<connects>
<connect gate="G$1" pin="1" pad="1"/>
<connect gate="G$1" pin="2" pad="2"/>
<connect gate="G$1" pin="3" pad="3"/>
<connect gate="G$1" pin="4" pad="4"/>
<connect gate="G$1" pin="5" pad="5"/>
<connect gate="G$1" pin="6" pad="6"/>
</connects>
<package3dinstances>
<package3dinstance package3d_urn="urn:adsk.eagle:package:8081635/1"/>
</package3dinstances>
<technologies>
<technology name="">
<attribute name="POPULARITY" value="0" constant="no"/>
</technology>
</technologies>
</device>
</devices>
</deviceset>
<deviceset name="MTA08-100" urn="urn:adsk.eagle:component:8082812/2" prefix="J" uservalue="yes" library_version="4">
<description>&lt;b&gt;AMP connector&lt;/b&gt;</description>
<gates>
<gate name="G$1" symbol="MTA-1_8" x="0" y="0"/>
</gates>
<devices>
<device name="" package="10X08MTA">
<connects>
<connect gate="G$1" pin="1" pad="1"/>
<connect gate="G$1" pin="2" pad="2"/>
<connect gate="G$1" pin="3" pad="3"/>
<connect gate="G$1" pin="4" pad="4"/>
<connect gate="G$1" pin="5" pad="5"/>
<connect gate="G$1" pin="6" pad="6"/>
<connect gate="G$1" pin="7" pad="7"/>
<connect gate="G$1" pin="8" pad="8"/>
</connects>
<package3dinstances>
<package3dinstance package3d_urn="urn:adsk.eagle:package:8081637/1"/>
</package3dinstances>
<technologies>
<technology name="">
<attribute name="POPULARITY" value="1" constant="no"/>
</technology>
</technologies>
</device>
</devices>
</deviceset>
<deviceset name="MTA10-100" urn="urn:adsk.eagle:component:8082822/2" prefix="J" uservalue="yes" library_version="4">
<description>&lt;b&gt;AMP connector&lt;/b&gt;</description>
<gates>
<gate name="G$3" symbol="MTA-1_10" x="0" y="0"/>
</gates>
<devices>
<device name="" package="10X10MTA">
<connects>
<connect gate="G$3" pin="1" pad="1"/>
<connect gate="G$3" pin="10" pad="10"/>
<connect gate="G$3" pin="2" pad="2"/>
<connect gate="G$3" pin="3" pad="3"/>
<connect gate="G$3" pin="4" pad="4"/>
<connect gate="G$3" pin="5" pad="5"/>
<connect gate="G$3" pin="6" pad="6"/>
<connect gate="G$3" pin="7" pad="7"/>
<connect gate="G$3" pin="8" pad="8"/>
<connect gate="G$3" pin="9" pad="9"/>
</connects>
<package3dinstances>
<package3dinstance package3d_urn="urn:adsk.eagle:package:8081639/1"/>
</package3dinstances>
<technologies>
<technology name="">
<attribute name="POPULARITY" value="0" constant="no"/>
</technology>
</technologies>
</device>
</devices>
</deviceset>
</devicesets>
</library>
</libraries>
<attributes>
</attributes>
<variantdefs>
</variantdefs>
<classes>
<class number="0" name="default" width="0" drill="0">
</class>
</classes>
<parts>
<part name="PLAYER-1" library="arduino" deviceset="ARDUINO_NANO2" device=""/>
<part name="SUPPLY2" library="supply2" library_urn="urn:adsk.eagle:library:372" deviceset="GND" device=""/>
<part name="SUPPLY1" library="supply2" library_urn="urn:adsk.eagle:library:372" deviceset="GND" device=""/>
<part name="SUPPLY3" library="supply2" library_urn="urn:adsk.eagle:library:372" deviceset="GND" device=""/>
<part name="P+1" library="supply1" library_urn="urn:adsk.eagle:library:371" deviceset="VCC" device=""/>
<part name="P+2" library="supply1" library_urn="urn:adsk.eagle:library:371" deviceset="VCC" device=""/>
<part name="SFC-PLAYER-1" library="con-amp" library_urn="urn:adsk.eagle:library:127" deviceset="MTA05-100" device="" package3d_urn="urn:adsk.eagle:package:8081622/1" value="PLAYER 1 SFC"/>
<part name="P1-JAMMA-A" library="con-amp" library_urn="urn:adsk.eagle:library:127" deviceset="MTA05-100" device="" package3d_urn="urn:adsk.eagle:package:8081622/1" value="PLAYER 1 JAMMA"/>
<part name="P1-JAMMA-B" library="con-amp" library_urn="urn:adsk.eagle:library:127" deviceset="MTA06-100" device="" package3d_urn="urn:adsk.eagle:package:8081635/1"/>
<part name="P+3" library="supply1" library_urn="urn:adsk.eagle:library:371" deviceset="VCC" device=""/>
<part name="SUPPLY4" library="supply2" library_urn="urn:adsk.eagle:library:372" deviceset="GND" device=""/>
<part name="EZ-KICK" library="con-amp" library_urn="urn:adsk.eagle:library:127" deviceset="MTA08-100" device="" package3d_urn="urn:adsk.eagle:package:8081637/1" value="EZ KICK HARNESS"/>
<part name="SUPPLY5" library="supply2" library_urn="urn:adsk.eagle:library:372" deviceset="GND" device=""/>
<part name="PLAYER-2" library="arduino" deviceset="ARDUINO_NANO2" device=""/>
<part name="P+4" library="supply1" library_urn="urn:adsk.eagle:library:371" deviceset="VCC" device=""/>
<part name="SUPPLY8" library="supply2" library_urn="urn:adsk.eagle:library:372" deviceset="GND" device=""/>
<part name="P+5" library="supply1" library_urn="urn:adsk.eagle:library:371" deviceset="VCC" device=""/>
<part name="SFC-PLAYER-2" library="con-amp" library_urn="urn:adsk.eagle:library:127" deviceset="MTA05-100" device="" package3d_urn="urn:adsk.eagle:package:8081622/1" value="PLAYER 2 SFC"/>
<part name="SUPPLY6" library="supply2" library_urn="urn:adsk.eagle:library:372" deviceset="GND" device=""/>
<part name="SUPPLY7" library="supply2" library_urn="urn:adsk.eagle:library:372" deviceset="GND" device=""/>
<part name="P2-JAMMA-A" library="con-amp" library_urn="urn:adsk.eagle:library:127" deviceset="MTA05-100" device="" package3d_urn="urn:adsk.eagle:package:8081622/1" value="PLAYER 2 JAMMA"/>
<part name="P2-JAMMA-B" library="con-amp" library_urn="urn:adsk.eagle:library:127" deviceset="MTA06-100" device="" package3d_urn="urn:adsk.eagle:package:8081635/1"/>
<part name="SUPPLY9" library="supply2" library_urn="urn:adsk.eagle:library:372" deviceset="GND" device=""/>
<part name="P+6" library="supply1" library_urn="urn:adsk.eagle:library:371" deviceset="VCC" device=""/>
<part name="CPS1-KICK" library="con-amp" library_urn="urn:adsk.eagle:library:127" deviceset="MTA10-100" device="" package3d_urn="urn:adsk.eagle:package:8081639/1" value="CPS1 KICK HARNESS"/>
</parts>
<sheets>
<sheet>
<plain>
</plain>
<instances>
<instance part="PLAYER-1" gate="MODUL" x="27.94" y="53.34" smashed="yes">
<attribute name="NAME" x="10.16" y="27.94" size="1.778" layer="95"/>
<attribute name="VALUE" x="15.24" y="60.96" size="1.778" layer="96"/>
</instance>
<instance part="SUPPLY2" gate="GND" x="58.42" y="-2.54" smashed="yes" rot="R270">
<attribute name="VALUE" x="55.245" y="-0.635" size="1.778" layer="96"/>
</instance>
<instance part="SUPPLY1" gate="GND" x="25.4" y="15.24" smashed="yes">
<attribute name="VALUE" x="23.495" y="12.065" size="1.778" layer="96"/>
</instance>
<instance part="SUPPLY3" gate="GND" x="33.02" y="15.24" smashed="yes">
<attribute name="VALUE" x="31.115" y="12.065" size="1.778" layer="96"/>
</instance>
<instance part="P+1" gate="VCC" x="22.86" y="91.44" smashed="yes">
<attribute name="VALUE" x="20.32" y="88.9" size="1.778" layer="96" rot="R90"/>
</instance>
<instance part="P+2" gate="VCC" x="73.66" y="-2.54" smashed="yes" rot="R270">
<attribute name="VALUE" x="71.12" y="0" size="1.778" layer="96"/>
</instance>
<instance part="SFC-PLAYER-1" gate="G$1" x="66.04" y="-7.62" smashed="yes" rot="R180">
<attribute name="NAME" x="58.42" y="-7.62" size="1.778" layer="95" rot="R180"/>
<attribute name="VALUE" x="58.42" y="-3.81" size="1.778" layer="96" rot="R180"/>
</instance>
<instance part="P1-JAMMA-A" gate="G$1" x="111.76" y="71.12" smashed="yes" rot="R270">
<attribute name="NAME" x="111.76" y="63.5" size="1.778" layer="95" rot="R90"/>
<attribute name="VALUE" x="107.95" y="63.5" size="1.778" layer="96" rot="R270"/>
</instance>
<instance part="P1-JAMMA-B" gate="G$1" x="111.76" y="58.42" smashed="yes" rot="R270">
<attribute name="NAME" x="111.76" y="48.26" size="1.778" layer="95" rot="R90"/>
<attribute name="VALUE" x="107.95" y="48.26" size="1.778" layer="96" rot="R270"/>
</instance>
<instance part="P+3" gate="VCC" x="106.68" y="81.28" smashed="yes">
<attribute name="VALUE" x="104.14" y="78.74" size="1.778" layer="96" rot="R90"/>
</instance>
<instance part="SUPPLY4" gate="GND" x="106.68" y="45.72" smashed="yes">
<attribute name="VALUE" x="104.775" y="42.545" size="1.778" layer="96"/>
</instance>
<instance part="EZ-KICK" gate="G$1" x="101.6" y="10.16" smashed="yes" rot="R180">
<attribute name="NAME" x="88.9" y="10.16" size="1.778" layer="95" rot="R180"/>
<attribute name="VALUE" x="88.9" y="13.97" size="1.778" layer="96" rot="R180"/>
</instance>
<instance part="SUPPLY5" gate="GND" x="116.84" y="10.16" smashed="yes">
<attribute name="VALUE" x="114.935" y="6.985" size="1.778" layer="96"/>
</instance>
<instance part="PLAYER-2" gate="MODUL" x="190.5" y="53.34" smashed="yes" rot="MR0">
<attribute name="NAME" x="208.28" y="27.94" size="1.778" layer="95" rot="MR0"/>
<attribute name="VALUE" x="203.2" y="60.96" size="1.778" layer="96" rot="MR0"/>
</instance>
<instance part="P+4" gate="VCC" x="195.58" y="91.44" smashed="yes">
<attribute name="VALUE" x="193.04" y="88.9" size="1.778" layer="96" rot="R90"/>
</instance>
<instance part="SUPPLY8" gate="GND" x="144.78" y="-2.54" smashed="yes" rot="R270">
<attribute name="VALUE" x="141.605" y="-0.635" size="1.778" layer="96"/>
</instance>
<instance part="P+5" gate="VCC" x="160.02" y="-2.54" smashed="yes" rot="R270">
<attribute name="VALUE" x="157.48" y="0" size="1.778" layer="96"/>
</instance>
<instance part="SFC-PLAYER-2" gate="G$1" x="152.4" y="-7.62" smashed="yes" rot="R180">
<attribute name="NAME" x="144.78" y="-7.62" size="1.778" layer="95" rot="R180"/>
<attribute name="VALUE" x="144.78" y="-3.81" size="1.778" layer="96" rot="R180"/>
</instance>
<instance part="SUPPLY6" gate="GND" x="185.42" y="15.24" smashed="yes">
<attribute name="VALUE" x="183.515" y="12.065" size="1.778" layer="96"/>
</instance>
<instance part="SUPPLY7" gate="GND" x="193.04" y="15.24" smashed="yes">
<attribute name="VALUE" x="191.135" y="12.065" size="1.778" layer="96"/>
</instance>
<instance part="P2-JAMMA-A" gate="G$1" x="119.38" y="71.12" smashed="yes" rot="R90">
<attribute name="NAME" x="119.38" y="78.74" size="1.778" layer="95" rot="R270"/>
<attribute name="VALUE" x="123.19" y="78.74" size="1.778" layer="96" rot="R90"/>
</instance>
<instance part="P2-JAMMA-B" gate="G$1" x="119.38" y="55.88" smashed="yes" rot="R90">
<attribute name="NAME" x="119.38" y="66.04" size="1.778" layer="95" rot="R270"/>
<attribute name="VALUE" x="123.19" y="66.04" size="1.778" layer="96" rot="R90"/>
</instance>
<instance part="SUPPLY9" gate="GND" x="124.46" y="45.72" smashed="yes">
<attribute name="VALUE" x="122.555" y="42.545" size="1.778" layer="96"/>
</instance>
<instance part="P+6" gate="VCC" x="124.46" y="81.28" smashed="yes">
<attribute name="VALUE" x="121.92" y="78.74" size="1.778" layer="96" rot="R90"/>
</instance>
<instance part="CPS1-KICK" gate="G$3" x="104.14" y="-7.62" smashed="yes" rot="R180">
<attribute name="NAME" x="88.9" y="-7.62" size="1.778" layer="95" rot="R180"/>
<attribute name="VALUE" x="88.9" y="-3.81" size="1.778" layer="96" rot="R180"/>
</instance>
</instances>
<busses>
</busses>
<nets>
<net name="GND" class="0">
<segment>
<pinref part="SUPPLY2" gate="GND" pin="GND"/>
<wire x1="60.96" y1="-2.54" x2="60.96" y2="-5.08" width="0.1524" layer="91"/>
<pinref part="SFC-PLAYER-1" gate="G$1" pin="5"/>
</segment>
<segment>
<pinref part="PLAYER-1" gate="MODUL" pin="COM"/>
<pinref part="SUPPLY1" gate="GND" pin="GND"/>
</segment>
<segment>
<pinref part="PLAYER-1" gate="MODUL" pin="COM@1"/>
<pinref part="SUPPLY3" gate="GND" pin="GND"/>
</segment>
<segment>
<pinref part="SUPPLY4" gate="GND" pin="GND"/>
<wire x1="106.68" y1="48.26" x2="106.68" y2="50.8" width="0.1524" layer="91"/>
<pinref part="P1-JAMMA-B" gate="G$1" pin="6"/>
<wire x1="106.68" y1="50.8" x2="109.22" y2="50.8" width="0.1524" layer="91"/>
</segment>
<segment>
<pinref part="EZ-KICK" gate="G$1" pin="2"/>
<wire x1="106.68" y1="12.7" x2="106.68" y2="15.24" width="0.1524" layer="91"/>
<wire x1="106.68" y1="15.24" x2="109.22" y2="15.24" width="0.1524" layer="91"/>
<pinref part="EZ-KICK" gate="G$1" pin="1"/>
<wire x1="109.22" y1="15.24" x2="109.22" y2="12.7" width="0.1524" layer="91"/>
<wire x1="109.22" y1="15.24" x2="116.84" y2="15.24" width="0.1524" layer="91"/>
<junction x="109.22" y="15.24"/>
<pinref part="SUPPLY5" gate="GND" pin="GND"/>
<wire x1="116.84" y1="15.24" x2="116.84" y2="12.7" width="0.1524" layer="91"/>
<wire x1="106.68" y1="12.7" x2="111.76" y2="-5.08" width="0.1524" layer="91"/>
<junction x="106.68" y="12.7"/>
<wire x1="109.22" y1="12.7" x2="114.3" y2="-5.08" width="0.1524" layer="91"/>
<junction x="109.22" y="12.7"/>
<pinref part="CPS1-KICK" gate="G$3" pin="1"/>
<pinref part="CPS1-KICK" gate="G$3" pin="2"/>
</segment>
<segment>
<pinref part="SUPPLY8" gate="GND" pin="GND"/>
<wire x1="147.32" y1="-2.54" x2="147.32" y2="-5.08" width="0.1524" layer="91"/>
<pinref part="SFC-PLAYER-2" gate="G$1" pin="5"/>
</segment>
<segment>
<pinref part="PLAYER-2" gate="MODUL" pin="COM@1"/>
<pinref part="SUPPLY6" gate="GND" pin="GND"/>
</segment>
<segment>
<pinref part="PLAYER-2" gate="MODUL" pin="COM"/>
<pinref part="SUPPLY7" gate="GND" pin="GND"/>
</segment>
<segment>
<pinref part="SUPPLY9" gate="GND" pin="GND"/>
<pinref part="P2-JAMMA-B" gate="G$1" pin="1"/>
<wire x1="124.46" y1="48.26" x2="124.46" y2="50.8" width="0.1524" layer="91"/>
<wire x1="124.46" y1="50.8" x2="121.92" y2="50.8" width="0.1524" layer="91"/>
</segment>
</net>
<net name="P1-JAMMA-UP" class="0">
<segment>
<pinref part="PLAYER-1" gate="MODUL" pin="D3"/>
<label x="81.28" y="73.66" size="1.778" layer="95"/>
<wire x1="53.34" y1="73.66" x2="109.22" y2="73.66" width="0.1524" layer="91"/>
<pinref part="P1-JAMMA-A" gate="G$1" pin="2"/>
</segment>
</net>
<net name="P1-JAMMA-DOWN" class="0">
<segment>
<pinref part="PLAYER-1" gate="MODUL" pin="D4"/>
<label x="81.28" y="71.12" size="1.778" layer="95"/>
<wire x1="53.34" y1="71.12" x2="109.22" y2="71.12" width="0.1524" layer="91"/>
<pinref part="P1-JAMMA-A" gate="G$1" pin="3"/>
</segment>
</net>
<net name="P1-JAMMA-LEFT" class="0">
<segment>
<pinref part="PLAYER-1" gate="MODUL" pin="D5"/>
<label x="81.28" y="68.58" size="1.778" layer="95"/>
<wire x1="53.34" y1="68.58" x2="109.22" y2="68.58" width="0.1524" layer="91"/>
<pinref part="P1-JAMMA-A" gate="G$1" pin="4"/>
</segment>
</net>
<net name="P1-JAMMA-RIGHT" class="0">
<segment>
<pinref part="PLAYER-1" gate="MODUL" pin="D6"/>
<label x="81.28" y="66.04" size="1.778" layer="95"/>
<wire x1="53.34" y1="66.04" x2="109.22" y2="66.04" width="0.1524" layer="91"/>
<pinref part="P1-JAMMA-A" gate="G$1" pin="5"/>
</segment>
</net>
<net name="P1-JAMMA-L-PUNCH" class="0">
<segment>
<pinref part="PLAYER-1" gate="MODUL" pin="D7"/>
<label x="81.28" y="63.5" size="1.778" layer="95"/>
<wire x1="53.34" y1="63.5" x2="109.22" y2="63.5" width="0.1524" layer="91"/>
<pinref part="P1-JAMMA-B" gate="G$1" pin="1"/>
</segment>
</net>
<net name="P1-JAMMA-M-PUNCH" class="0">
<segment>
<pinref part="PLAYER-1" gate="MODUL" pin="D8"/>
<label x="81.28" y="60.96" size="1.778" layer="95"/>
<wire x1="53.34" y1="60.96" x2="109.22" y2="60.96" width="0.1524" layer="91"/>
<pinref part="P1-JAMMA-B" gate="G$1" pin="2"/>
</segment>
</net>
<net name="P1-JAMMA-H-PUNCH" class="0">
<segment>
<pinref part="PLAYER-1" gate="MODUL" pin="D9"/>
<label x="81.28" y="58.42" size="1.778" layer="95"/>
<wire x1="53.34" y1="58.42" x2="109.22" y2="58.42" width="0.1524" layer="91"/>
<pinref part="P1-JAMMA-B" gate="G$1" pin="3"/>
</segment>
</net>
<net name="P1-JAMMA-START" class="0">
<segment>
<pinref part="PLAYER-1" gate="MODUL" pin="D10"/>
<label x="81.28" y="55.88" size="1.778" layer="95"/>
<wire x1="53.34" y1="55.88" x2="109.22" y2="55.88" width="0.1524" layer="91"/>
<pinref part="P1-JAMMA-B" gate="G$1" pin="4"/>
</segment>
</net>
<net name="P1-JAMMA-COIN" class="0">
<segment>
<pinref part="PLAYER-1" gate="MODUL" pin="D11/MOSI"/>
<label x="81.28" y="53.34" size="1.778" layer="95"/>
<wire x1="53.34" y1="53.34" x2="109.22" y2="53.34" width="0.1524" layer="91"/>
<pinref part="P1-JAMMA-B" gate="G$1" pin="5"/>
</segment>
</net>
<net name="P1-LED" class="0">
<segment>
<pinref part="PLAYER-1" gate="MODUL" pin="D13/SCK"/>
<wire x1="53.34" y1="48.26" x2="81.28" y2="48.26" width="0.1524" layer="91"/>
<label x="81.28" y="48.26" size="1.778" layer="95"/>
</segment>
</net>
<net name="P1-M-KICK" class="0">
<segment>
<pinref part="PLAYER-1" gate="MODUL" pin="A4"/>
<wire x1="53.34" y1="35.56" x2="99.06" y2="35.56" width="0.1524" layer="91"/>
<label x="81.28" y="35.56" size="1.778" layer="95"/>
<pinref part="EZ-KICK" gate="G$1" pin="5"/>
<wire x1="99.06" y1="35.56" x2="99.06" y2="12.7" width="0.1524" layer="91"/>
<junction x="99.06" y="12.7"/>
<pinref part="CPS1-KICK" gate="G$3" pin="4"/>
<wire x1="99.06" y1="12.7" x2="106.68" y2="-5.08" width="0.1524" layer="91"/>
</segment>
</net>
<net name="P1-L-KICK" class="0">
<segment>
<pinref part="PLAYER-1" gate="MODUL" pin="A3"/>
<wire x1="53.34" y1="33.02" x2="104.14" y2="33.02" width="0.1524" layer="91"/>
<label x="81.28" y="33.02" size="1.778" layer="95"/>
<pinref part="EZ-KICK" gate="G$1" pin="3"/>
<wire x1="104.14" y1="33.02" x2="104.14" y2="12.7" width="0.1524" layer="91"/>
<pinref part="CPS1-KICK" gate="G$3" pin="3"/>
<wire x1="104.14" y1="12.7" x2="109.22" y2="-5.08" width="0.1524" layer="91"/>
<junction x="104.14" y="12.7"/>
</segment>
</net>
<net name="VCC" class="0">
<segment>
<pinref part="PLAYER-1" gate="MODUL" pin="+5V"/>
<pinref part="P+1" gate="VCC" pin="VCC"/>
</segment>
<segment>
<pinref part="P+2" gate="VCC" pin="VCC"/>
<wire x1="71.12" y1="-2.54" x2="71.12" y2="-5.08" width="0.1524" layer="91"/>
<pinref part="SFC-PLAYER-1" gate="G$1" pin="1"/>
</segment>
<segment>
<pinref part="P+3" gate="VCC" pin="VCC"/>
<wire x1="106.68" y1="78.74" x2="106.68" y2="76.2" width="0.1524" layer="91"/>
<pinref part="P1-JAMMA-A" gate="G$1" pin="1"/>
<wire x1="106.68" y1="76.2" x2="109.22" y2="76.2" width="0.1524" layer="91"/>
</segment>
<segment>
<pinref part="PLAYER-2" gate="MODUL" pin="+5V"/>
<pinref part="P+4" gate="VCC" pin="VCC"/>
</segment>
<segment>
<pinref part="P+5" gate="VCC" pin="VCC"/>
<wire x1="157.48" y1="-2.54" x2="157.48" y2="-5.08" width="0.1524" layer="91"/>
<pinref part="SFC-PLAYER-2" gate="G$1" pin="1"/>
</segment>
<segment>
<pinref part="P2-JAMMA-A" gate="G$1" pin="5"/>
<pinref part="P+6" gate="VCC" pin="VCC"/>
<wire x1="121.92" y1="76.2" x2="124.46" y2="76.2" width="0.1524" layer="91"/>
<wire x1="124.46" y1="76.2" x2="124.46" y2="78.74" width="0.1524" layer="91"/>
</segment>
</net>
<net name="P2-H-KICK" class="0">
<segment>
<pinref part="PLAYER-2" gate="MODUL" pin="A5"/>
<wire x1="165.1" y1="38.1" x2="134.62" y2="38.1" width="0.1524" layer="91"/>
<wire x1="134.62" y1="38.1" x2="134.62" y2="27.94" width="0.1524" layer="91"/>
<label x="142.24" y="38.1" size="1.778" layer="95"/>
<pinref part="EZ-KICK" gate="G$1" pin="8"/>
<wire x1="134.62" y1="27.94" x2="91.44" y2="27.94" width="0.1524" layer="91"/>
<wire x1="91.44" y1="27.94" x2="91.44" y2="12.7" width="0.1524" layer="91"/>
<junction x="91.44" y="12.7"/>
<pinref part="CPS1-KICK" gate="G$3" pin="9"/>
<wire x1="91.44" y1="12.7" x2="93.98" y2="-5.08" width="0.1524" layer="91"/>
</segment>
</net>
<net name="P2-M-KICK" class="0">
<segment>
<pinref part="PLAYER-2" gate="MODUL" pin="A4"/>
<wire x1="165.1" y1="35.56" x2="137.16" y2="35.56" width="0.1524" layer="91"/>
<wire x1="137.16" y1="35.56" x2="137.16" y2="25.4" width="0.1524" layer="91"/>
<label x="142.24" y="35.56" size="1.778" layer="95"/>
<pinref part="EZ-KICK" gate="G$1" pin="6"/>
<wire x1="137.16" y1="25.4" x2="96.52" y2="25.4" width="0.1524" layer="91"/>
<wire x1="96.52" y1="25.4" x2="96.52" y2="12.7" width="0.1524" layer="91"/>
<junction x="96.52" y="12.7"/>
<pinref part="CPS1-KICK" gate="G$3" pin="8"/>
<wire x1="96.52" y1="12.7" x2="96.52" y2="-5.08" width="0.1524" layer="91"/>
</segment>
</net>
<net name="P1-H-KICK" class="0">
<segment>
<pinref part="PLAYER-1" gate="MODUL" pin="A5"/>
<wire x1="53.34" y1="38.1" x2="93.98" y2="38.1" width="0.1524" layer="91"/>
<label x="81.28" y="38.1" size="1.778" layer="95"/>
<pinref part="EZ-KICK" gate="G$1" pin="7"/>
<wire x1="93.98" y1="12.7" x2="93.98" y2="38.1" width="0.1524" layer="91"/>
<wire x1="93.98" y1="12.7" x2="104.14" y2="-5.08" width="0.1524" layer="91"/>
<junction x="93.98" y="12.7"/>
<pinref part="CPS1-KICK" gate="G$3" pin="5"/>
</segment>
</net>
<net name="P2-L-KICK" class="0">
<segment>
<pinref part="PLAYER-2" gate="MODUL" pin="A3"/>
<wire x1="165.1" y1="33.02" x2="139.7" y2="33.02" width="0.1524" layer="91"/>
<wire x1="139.7" y1="33.02" x2="139.7" y2="22.86" width="0.1524" layer="91"/>
<label x="142.24" y="33.02" size="1.778" layer="95"/>
<pinref part="EZ-KICK" gate="G$1" pin="4"/>
<wire x1="139.7" y1="22.86" x2="101.6" y2="22.86" width="0.1524" layer="91"/>
<wire x1="101.6" y1="22.86" x2="101.6" y2="12.7" width="0.1524" layer="91"/>
<junction x="101.6" y="12.7"/>
<pinref part="CPS1-KICK" gate="G$3" pin="7"/>
<wire x1="101.6" y1="12.7" x2="99.06" y2="-5.08" width="0.1524" layer="91"/>
</segment>
</net>
<net name="P1-SFC-LATCH" class="0">
<segment>
<pinref part="PLAYER-1" gate="MODUL" pin="A2"/>
<pinref part="SFC-PLAYER-1" gate="G$1" pin="2"/>
<wire x1="53.34" y1="30.48" x2="68.58" y2="30.48" width="0.1524" layer="91"/>
<wire x1="68.58" y1="30.48" x2="68.58" y2="-5.08" width="0.1524" layer="91"/>
<label x="68.58" y="20.32" size="1.778" layer="95" rot="R270"/>
</segment>
</net>
<net name="P1-SFC-CLOCK" class="0">
<segment>
<pinref part="PLAYER-1" gate="MODUL" pin="A1"/>
<pinref part="SFC-PLAYER-1" gate="G$1" pin="3"/>
<wire x1="53.34" y1="27.94" x2="66.04" y2="27.94" width="0.1524" layer="91"/>
<wire x1="66.04" y1="27.94" x2="66.04" y2="-5.08" width="0.1524" layer="91"/>
<label x="66.04" y="20.32" size="1.778" layer="95" rot="R270"/>
</segment>
</net>
<net name="P1-SFC-DATA" class="0">
<segment>
<pinref part="PLAYER-1" gate="MODUL" pin="A0"/>
<pinref part="SFC-PLAYER-1" gate="G$1" pin="4"/>
<wire x1="53.34" y1="25.4" x2="63.5" y2="25.4" width="0.1524" layer="91"/>
<wire x1="63.5" y1="25.4" x2="63.5" y2="-5.08" width="0.1524" layer="91"/>
<label x="63.5" y="20.32" size="1.778" layer="95" rot="R270"/>
</segment>
</net>
<net name="P2-SFC-DATA" class="0">
<segment>
<pinref part="SFC-PLAYER-2" gate="G$1" pin="4"/>
<wire x1="149.86" y1="25.4" x2="149.86" y2="-5.08" width="0.1524" layer="91"/>
<label x="149.86" y="20.32" size="1.778" layer="95" rot="R270"/>
<pinref part="PLAYER-2" gate="MODUL" pin="A0"/>
<wire x1="149.86" y1="25.4" x2="165.1" y2="25.4" width="0.1524" layer="91"/>
</segment>
</net>
<net name="P2-SFC-CLOCK" class="0">
<segment>
<pinref part="SFC-PLAYER-2" gate="G$1" pin="3"/>
<wire x1="152.4" y1="27.94" x2="152.4" y2="-5.08" width="0.1524" layer="91"/>
<label x="152.4" y="20.32" size="1.778" layer="95" rot="R270"/>
<pinref part="PLAYER-2" gate="MODUL" pin="A1"/>
<wire x1="152.4" y1="27.94" x2="165.1" y2="27.94" width="0.1524" layer="91"/>
</segment>
</net>
<net name="P2-SFC-LATCH" class="0">
<segment>
<pinref part="SFC-PLAYER-2" gate="G$1" pin="2"/>
<wire x1="154.94" y1="30.48" x2="154.94" y2="-5.08" width="0.1524" layer="91"/>
<label x="154.94" y="20.32" size="1.778" layer="95" rot="R270"/>
<pinref part="PLAYER-2" gate="MODUL" pin="A2"/>
<wire x1="154.94" y1="30.48" x2="165.1" y2="30.48" width="0.1524" layer="91"/>
</segment>
</net>
<net name="P2-JAMMA-UP" class="0">
<segment>
<pinref part="P2-JAMMA-A" gate="G$1" pin="4"/>
<pinref part="PLAYER-2" gate="MODUL" pin="D3"/>
<wire x1="121.92" y1="73.66" x2="165.1" y2="73.66" width="0.1524" layer="91"/>
<label x="137.16" y="73.66" size="1.778" layer="95"/>
</segment>
</net>
<net name="P2-JAMMA-DOWN" class="0">
<segment>
<pinref part="PLAYER-2" gate="MODUL" pin="D4"/>
<pinref part="P2-JAMMA-A" gate="G$1" pin="3"/>
<wire x1="165.1" y1="71.12" x2="121.92" y2="71.12" width="0.1524" layer="91"/>
<label x="137.16" y="71.12" size="1.778" layer="95"/>
</segment>
</net>
<net name="P2-JAMMA-LEFT" class="0">
<segment>
<pinref part="P2-JAMMA-A" gate="G$1" pin="2"/>
<pinref part="PLAYER-2" gate="MODUL" pin="D5"/>
<wire x1="121.92" y1="68.58" x2="165.1" y2="68.58" width="0.1524" layer="91"/>
<label x="137.16" y="68.58" size="1.778" layer="95"/>
</segment>
</net>
<net name="P2-JAMMA-RIGHT" class="0">
<segment>
<pinref part="PLAYER-2" gate="MODUL" pin="D6"/>
<pinref part="P2-JAMMA-A" gate="G$1" pin="1"/>
<wire x1="165.1" y1="66.04" x2="121.92" y2="66.04" width="0.1524" layer="91"/>
<label x="137.16" y="66.04" size="1.778" layer="95"/>
</segment>
</net>
<net name="P2-JAMMA-L-PUNCH" class="0">
<segment>
<pinref part="P2-JAMMA-B" gate="G$1" pin="6"/>
<pinref part="PLAYER-2" gate="MODUL" pin="D7"/>
<wire x1="121.92" y1="63.5" x2="165.1" y2="63.5" width="0.1524" layer="91"/>
<label x="137.16" y="63.5" size="1.778" layer="95"/>
</segment>
</net>
<net name="P2-JAMMA-M-PUNCH" class="0">
<segment>
<pinref part="PLAYER-2" gate="MODUL" pin="D8"/>
<pinref part="P2-JAMMA-B" gate="G$1" pin="5"/>
<wire x1="165.1" y1="60.96" x2="121.92" y2="60.96" width="0.1524" layer="91"/>
<label x="137.16" y="60.96" size="1.778" layer="95"/>
</segment>
</net>
<net name="P2-JAMMA-H-PUNCH" class="0">
<segment>
<pinref part="P2-JAMMA-B" gate="G$1" pin="4"/>
<pinref part="PLAYER-2" gate="MODUL" pin="D9"/>
<wire x1="121.92" y1="58.42" x2="165.1" y2="58.42" width="0.1524" layer="91"/>
<label x="137.16" y="58.42" size="1.778" layer="95"/>
</segment>
</net>
<net name="P2-JAMMA-START" class="0">
<segment>
<pinref part="PLAYER-2" gate="MODUL" pin="D10"/>
<pinref part="P2-JAMMA-B" gate="G$1" pin="3"/>
<wire x1="165.1" y1="55.88" x2="121.92" y2="55.88" width="0.1524" layer="91"/>
<label x="137.16" y="55.88" size="1.778" layer="95"/>
</segment>
</net>
<net name="P2-JAMMA-COIN" class="0">
<segment>
<pinref part="P2-JAMMA-B" gate="G$1" pin="2"/>
<pinref part="PLAYER-2" gate="MODUL" pin="D11/MOSI"/>
<wire x1="121.92" y1="53.34" x2="165.1" y2="53.34" width="0.1524" layer="91"/>
<label x="137.16" y="53.34" size="1.778" layer="95"/>
</segment>
</net>
<net name="P2-LED" class="0">
<segment>
<pinref part="PLAYER-2" gate="MODUL" pin="D13/SCK"/>
<wire x1="165.1" y1="48.26" x2="137.16" y2="48.26" width="0.1524" layer="91"/>
<label x="137.16" y="48.26" size="1.778" layer="95"/>
</segment>
</net>
<net name="N$5" class="0">
<segment>
<pinref part="PLAYER-1" gate="MODUL" pin="3V3"/>
<wire x1="30.48" y1="88.9" x2="30.48" y2="91.44" width="0.1524" layer="91"/>
</segment>
</net>
<net name="N$6" class="0">
<segment>
<pinref part="PLAYER-1" gate="MODUL" pin="AREF"/>
<wire x1="35.56" y1="88.9" x2="35.56" y2="91.44" width="0.1524" layer="91"/>
</segment>
</net>
<net name="N$7" class="0">
<segment>
<pinref part="PLAYER-1" gate="MODUL" pin="VIN"/>
<wire x1="17.78" y1="88.9" x2="17.78" y2="91.44" width="0.1524" layer="91"/>
</segment>
</net>
<net name="N$8" class="0">
<segment>
<pinref part="PLAYER-2" gate="MODUL" pin="AREF"/>
<wire x1="182.88" y1="88.9" x2="182.88" y2="91.44" width="0.1524" layer="91"/>
</segment>
</net>
<net name="N$9" class="0">
<segment>
<pinref part="PLAYER-2" gate="MODUL" pin="3V3"/>
<wire x1="187.96" y1="88.9" x2="187.96" y2="91.44" width="0.1524" layer="91"/>
</segment>
</net>
<net name="N$10" class="0">
<segment>
<pinref part="PLAYER-2" gate="MODUL" pin="VIN"/>
<wire x1="200.66" y1="88.9" x2="200.66" y2="91.44" width="0.1524" layer="91"/>
</segment>
</net>
<net name="N$11" class="0">
<segment>
<pinref part="PLAYER-2" gate="MODUL" pin="D2"/>
<wire x1="165.1" y1="76.2" x2="162.56" y2="76.2" width="0.1524" layer="91"/>
</segment>
</net>
<net name="N$12" class="0">
<segment>
<pinref part="PLAYER-2" gate="MODUL" pin="D0/RX"/>
<wire x1="165.1" y1="78.74" x2="162.56" y2="78.74" width="0.1524" layer="91"/>
</segment>
</net>
<net name="N$13" class="0">
<segment>
<pinref part="PLAYER-2" gate="MODUL" pin="D1/TX"/>
<wire x1="165.1" y1="81.28" x2="162.56" y2="81.28" width="0.1524" layer="91"/>
</segment>
</net>
<net name="N$14" class="0">
<segment>
<pinref part="PLAYER-2" gate="MODUL" pin="RESET"/>
<wire x1="215.9" y1="73.66" x2="218.44" y2="73.66" width="0.1524" layer="91"/>
</segment>
</net>
<net name="N$15" class="0">
<segment>
<pinref part="PLAYER-2" gate="MODUL" pin="RESET@2"/>
<wire x1="215.9" y1="71.12" x2="218.44" y2="71.12" width="0.1524" layer="91"/>
</segment>
</net>
<net name="N$16" class="0">
<segment>
<pinref part="PLAYER-2" gate="MODUL" pin="A7"/>
<wire x1="165.1" y1="43.18" x2="162.56" y2="43.18" width="0.1524" layer="91"/>
</segment>
</net>
<net name="N$17" class="0">
<segment>
<pinref part="PLAYER-2" gate="MODUL" pin="A6"/>
<wire x1="165.1" y1="40.64" x2="162.56" y2="40.64" width="0.1524" layer="91"/>
</segment>
</net>
<net name="N$18" class="0">
<segment>
<pinref part="PLAYER-1" gate="MODUL" pin="A7"/>
<wire x1="53.34" y1="43.18" x2="55.88" y2="43.18" width="0.1524" layer="91"/>
</segment>
</net>
<net name="N$19" class="0">
<segment>
<pinref part="PLAYER-1" gate="MODUL" pin="A6"/>
<wire x1="53.34" y1="40.64" x2="55.88" y2="40.64" width="0.1524" layer="91"/>
</segment>
</net>
<net name="N$20" class="0">
<segment>
<pinref part="PLAYER-1" gate="MODUL" pin="D1/TX"/>
<wire x1="53.34" y1="81.28" x2="55.88" y2="81.28" width="0.1524" layer="91"/>
</segment>
</net>
<net name="N$21" class="0">
<segment>
<pinref part="PLAYER-1" gate="MODUL" pin="D0/RX"/>
<wire x1="53.34" y1="78.74" x2="55.88" y2="78.74" width="0.1524" layer="91"/>
</segment>
</net>
<net name="N$22" class="0">
<segment>
<pinref part="PLAYER-1" gate="MODUL" pin="D2"/>
<wire x1="53.34" y1="76.2" x2="55.88" y2="76.2" width="0.1524" layer="91"/>
</segment>
</net>
<net name="N$23" class="0">
<segment>
<pinref part="PLAYER-1" gate="MODUL" pin="RESET"/>
<wire x1="2.54" y1="73.66" x2="0" y2="73.66" width="0.1524" layer="91"/>
</segment>
</net>
<net name="N$24" class="0">
<segment>
<pinref part="PLAYER-1" gate="MODUL" pin="RESET@2"/>
<wire x1="2.54" y1="71.12" x2="0" y2="71.12" width="0.1524" layer="91"/>
</segment>
</net>
</nets>
</sheet>
</sheets>
</schematic>
</drawing>
<compatibility>
<note version="8.2" severity="warning">
Since Version 8.2, EAGLE supports online libraries. The ids
of those online libraries will not be understood (or retained)
with this version.
</note>
<note version="8.3" severity="warning">
Since Version 8.3, EAGLE supports URNs for individual library
assets (packages, symbols, and devices). The URNs of those assets
will not be understood (or retained) with this version.
</note>
<note version="8.3" severity="warning">
Since Version 8.3, EAGLE supports the association of 3D packages
with devices in libraries, schematics, and board files. Those 3D
packages will not be understood (or retained) with this version.
</note>
</compatibility>
</eagle>
